<a href="https://colab.research.google.com/github/azizhina51-svg/NLP/blob/main/Lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
faqs = """The Ministry of Information Technology and Telecommunication (MoITT), in partnership with Meta, today, hosted “Future in Focus: AI and Innovation,” an event dedicated to advancing digital transformation in Pakistan. The gathering brought together government leaders, industry experts, and academia to accelerate the adoption of artificial intelligence (AI) and digital innovation nationwide.
During the event, a series of initiatives designed to empower Pakistan’s public sector and the local community were announced. Among these, Meta revealed the expansion of Meta AI’s language capabilities, ALIF, enabling users in Pakistan to interact with Meta AI not only in English but also in Urdu. This enhancement empowers more people to discover information, express themselves, and maintain connections with what matters most.
Federal Minister for Information Technology and Telecommunication, Shaza Fatima Khawaja inaugurated the event. She stated, “Under the Prime Minister’s Digital Nation Vision, Pakistan is accelerating toward a future where technology empowers every citizen. Our National AI Policy and partnership with Meta reflects this commitment; advancing AI literacy, digital transformation, and innovation across government and academia. The introduction of ALIF - Urdu for Meta AI is a milestone in making technology more inclusive and accessible for our people, ensuring that no one is left behind in our digital transformation.”
The company also introduced the localized version of the “Transforming Public Sector Innovation in Asia Pacific with Llama” guide, developed in partnership with Deloitte. This guide, with support from the Ministry, demonstrates how Meta’s open-source AI model, Llama, can streamline government operations, enhance public services, and support data sovereignty.
Sarim Aziz, Director of Public Policy South and Central Asia at Meta, said, “Meta is deeply committed to supporting Pakistan’s vision for AI-driven growth and innovation. Through our collaboration with MoITT, HEC, and NCEAC, and the launch of these new initiatives, we aim to help the public sector and academia harness AI to drive digital transformation for the benefit of people across Pakistan. We’re also excited to announce that Meta AI now supports Urdu, opening up new opportunities for the local communities to engage with technology in their own language.”
Fizza Amjad, CEO of atomcamp. “By equipping non-technical faculty with AI knowledge, we’re creating a ripple effect that will reach thousands of students and strengthen the link between academia and industry, This initiative ensures that AI understanding extends beyond computer science, shaping how future professionals across disciplines engage with emerging technologies. It’s a step toward building a more AI-literate academic ecosystem in Pakistan.”
Earlier this year, Ministry of IT&T, in collaboration with Meta, the Higher Education Commission (HEC), National Computing and Emerging Sciences Accreditation Council (NCEAC) and Atomcamp, announced the launch of an AI Literacy Programme aimed at upskilling 350 non-Computer Science faculty members across Pakistani universities, equipping them with core AI competencies to prepare the next generation for the future of work."""

In [3]:
!pip install tensorflow

In [6]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [7]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [8]:
tokenizer = Tokenizer()

In [9]:
tokenizer.fit_on_texts([faqs])

In [10]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'ai': 3,
 'of': 4,
 'in': 5,
 'with': 6,
 'to': 7,
 'meta': 8,
 'for': 9,
 'digital': 10,
 'a': 11,
 'technology': 12,
 'innovation': 13,
 'pakistan': 14,
 'public': 15,
 'this': 16,
 '”': 17,
 'transformation': 18,
 'academia': 19,
 'is': 20,
 'our': 21,
 'across': 22,
 'that': 23,
 'ministry': 24,
 'information': 25,
 'partnership': 26,
 'event': 27,
 'government': 28,
 'sector': 29,
 'also': 30,
 'urdu': 31,
 'more': 32,
 'people': 33,
 'future': 34,
 'telecommunication': 35,
 'moitt': 36,
 'an': 37,
 'advancing': 38,
 'industry': 39,
 'initiatives': 40,
 'pakistan’s': 41,
 'local': 42,
 'announced': 43,
 'these': 44,
 'language': 45,
 'alif': 46,
 'empowers': 47,
 'vision': 48,
 'toward': 49,
 'national': 50,
 'policy': 51,
 'literacy': 52,
 'asia': 53,
 'guide': 54,
 'support': 55,
 'how': 56,
 'at': 57,
 'collaboration': 58,
 'hec': 59,
 'nceac': 60,
 'launch': 61,
 'new': 62,
 'we’re': 63,
 'engage': 64,
 'atomcamp': 65,
 'equipping': 66,
 'non': 67,
 'fac

In [11]:
len(tokenizer.word_index)

249

In [12]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [13]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [14]:
input_sequences

[[1, 24],
 [1, 24, 4],
 [1, 24, 4, 25],
 [1, 24, 4, 25, 12],
 [1, 24, 4, 25, 12, 2],
 [1, 24, 4, 25, 12, 2, 35],
 [1, 24, 4, 25, 12, 2, 35, 36],
 [1, 24, 4, 25, 12, 2, 35, 36, 5],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8, 72],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8, 72, 73],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8, 72, 73, 74],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8, 72, 73, 74, 5],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8, 72, 73, 74, 5, 75],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8, 72, 73, 74, 5, 75, 3],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8, 72, 73, 74, 5, 75, 3, 2],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8, 72, 73, 74, 5, 75, 3, 2, 13],
 [1, 24, 4, 25, 12, 2, 35, 36, 5, 26, 6, 8, 72, 73, 74, 5, 75, 3, 2, 13, 17],
 [1,
  24,
  4,
  25,
  12,
  2,
  35,
  36,
  5,
  26,
  6,
  8,
  72,
  73,
  74,
  5,
  75,
  3,
  2,
  13,
  17,
  37]

In [15]:
max_len = max([len(x) for x in input_sequences])
max_len

92

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [17]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,   1,  24],
       [  0,   0,   0, ...,   1,  24,   4],
       [  0,   0,   0, ...,  24,   4,  25],
       ...,
       [  0,   0,   0, ...,   9,   1,  34],
       [  0,   0,   0, ...,   1,  34,   4],
       [  0,   0,   0, ...,  34,   4, 249]], dtype=int32)

In [18]:
X = padded_input_sequences[:,:-1]
X

array([[  0,   0,   0, ...,   0,   0,   1],
       [  0,   0,   0, ...,   0,   1,  24],
       [  0,   0,   0, ...,   1,  24,   4],
       ...,
       [  0,   0,   0, ..., 248,   9,   1],
       [  0,   0,   0, ...,   9,   1,  34],
       [  0,   0,   0, ...,   1,  34,   4]], dtype=int32)

In [19]:
y = padded_input_sequences[:,-1]
y

array([ 24,   4,  25,  12,   2,  35,  36,   5,  26,   6,   8,  72,  73,
        74,   5,  75,   3,   2,  13,  17,  37,  27,  76,   7,  38,  10,
        18,   5,  14,   1,  77,  78,  79,  28,  80,  39,  81,   2,  19,
         7,  82,   1,  83,   4,  84,  85,   3,   2,  10,  13,  86,   1,
        27,  11,  88,   4,  40,  89,   7,  90,  41,  15,  29,   2,   1,
        42,  91,  92,  43,  93,  44,   8,  94,   1,  95,   4,   8,  96,
        45,  97,  46,  98,  99,   5,  14,   7, 100,   6,   8,   3, 101,
       102,   5, 103, 104,  30,   5,  31,  16, 105,  47,  32,  33,   7,
       106,  25, 107, 108,   2, 109, 110,   6, 111, 112, 113, 115,   9,
        25,  12,   2,  35, 116, 117, 118, 119,   1,  27, 120, 121, 122,
         1, 123, 124,  10, 125,  48,  14,  20, 126,  49,  11,  34, 127,
        12,  47, 128, 129,  21,  50,   3,  51,   2,  26,   6,   8, 130,
        16, 131,  38,   3,  52,  10,  18,   2,  13,  22,  28,   2,  19,
         1, 132,   4,  46,  31,   9,   8,   3,  20,  11, 133,   

In [20]:
X.shape

(468, 91)

In [21]:
y.shape

(468,)

In [22]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=283)

In [23]:
y.shape

(468, 283)

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [25]:
model = Sequential()
model.add(Embedding(283, 100, input_length=56))
model.add(LSTM(150))
model.add(Dense(283, activation='softmax'))

model.build(input_shape=(None, 56))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [26]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [27]:

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 56, 100)        │        28,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 283)            │        42,733 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221,633 (865.75 KB)

 Trainable params: 221,633 (865.75 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.fit(X,y,epochs=100)

Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 4s 133ms/step - accuracy: 0.0145 - loss: 5.6430
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 169ms/step - accuracy: 0.0412 - loss: 5.4181
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 165ms/step - accuracy: 0.0367 - loss: 5.1617
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 2s 135ms/step - accuracy: 0.0382 - loss: 5.0758
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 131ms/step - accuracy: 0.0592 - loss: 5.0443
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 133ms/step - accuracy: 0.0310 - loss: 5.0507
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 2s 158ms/step - accuracy: 0.0390 - loss: 5.0458
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 178ms/step - accuracy: 0.0577 - loss: 4.9777
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 2s 134ms/step - accuracy: 0.0715 - loss: 4.9808
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 134ms/step - accuracy: 0.0750 - loss: 4.8255
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 135ms/step - accuracy: 0.0955 - loss: 4.7793
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 2

In [30]:
import numpy as np
import time
text = "The Ministry of"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
The Ministry of information
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
The Ministry of information technology
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
The Ministry of information technology and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
The Ministry of information technology and telecommunication
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
The Ministry of information technology and telecommunication moitt
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
The Ministry of information technology and telecommunication moitt in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
The Ministry of information technology and telecommunication moitt in partnership
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
The Ministry of information technology and telecommunication moitt in partnership with
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
The Ministry of information technology and telecommunication moitt in partnership with meta
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
The Ministry of information technology and telecomm